version: '2'

services:
  galaxyzoo:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9294:9294
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}